INSERT INTO `items` (`name`, `label`, `limit`) VALUES  
    ('jager', 'Jägermeister', 5),
    ('vodka', 'Vodka', 5),
    ('rhum', 'Rhum', 5),
    ('whisky', 'Whisky', 5),
    ('tequila', 'Tequila', 5),
    ('martini', 'Martini Bianco', 5),
    -- ('soda', 'Soda', 5),
    ('jusfruit', 'Succo di frutta', 5),
    ('icetea', 'Ice Tea', 5),
    ('energy', 'Bevanda energetica', 5),
    ('drpepper', 'Dr. Pepper', 5),
    ('limonade', 'Limonata', 5),
    ('bolcacahuetes', 'Ciotola di noccioline', 5),
    ('bolnoixcajou', 'Ciotola di anacardi', 5),
    ('bolpistache', 'Ciotola di pistacchi', 5),
    ('bolchips', 'Ciotola di patatine', 5),
    ('saucisson', 'Salsiccia', 5),
    ('grapperaisin', 'Grappolo uva', 5),
    ('jagerbomb', 'Jägerbomb', 5),
    ('golem', 'Golem', 5),
    ('whiskycoca', 'Whisky-coke', 5),
    ('vodkaenergy', 'Vodka-energetica', 5),
    ('vodkafruit', 'Vodka-alla frutta', 5),
    ('rhumfruit', 'Rhum-alla frutta', 5),
    ('teqpaf', "Teq'paf", 5),
    ('rhumcoca', 'Rhum-coke', 5),
    ('mojito', 'Mojito', 5),
    ('ice', 'Ghiaccio', 5),
    ('mixapero', 'Mix di aperitivi', 3),
    ('metreshooter', 'Misuratore sparatutto', 3),
    ('jagercerbere', 'Jäger Cerberus', 3),
    ('menthe', 'Foglia di menta', 10)
;