anims = {
    {dic = "gestures@f@standing@casual", anim = "gesture_bring_it_on", label = "Prendilo", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_bye_hard", label = "Arrivederci", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_come_here_hard", label = "Vieni qui", category = "Gesture", loop = 0},
    {dic = "missheist_agency3aig_24", anim = "agent01_conversation", label = "Conversazione", category = "Misc", loop = 0},
    {dic = "misscarstealfinalecar_5_ig_3", anim = "crouchloop", label = "Nasconditi", category = "Misc", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_damn", label = "Dannazione", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_displeased", label = "Scontento", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_easy_now", label = "Facile ora", category = "Gesture", loop = 0},
	{dic = "mp_sleep", anim = "sleep_introfemale", label = "Fall asleep", category = "Misc", loop = 50},
    {dic = "gestures@f@standing@casual", anim = "gesture_hello", label = "Ciao!", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "getsure_its_mine", label = "È mio", category = "Gesture", loop = 0},
    {dic = "missfam4leadinoutmcs2", anim = "tracy_loop", label = "Inginocchiati sul terreno sconvolto", category = "Misc", loop = 0},
    {dic = "mp_safehouse", anim = "lap_dance_girl", label = "Lap Dance", category = "Misc", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_me", label = "Me", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_head_no", label = "No", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_no_way", label = "Non c'è modo", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_pleased", label = "Contento", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_point", label = "Punta", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_shrug_hard", label = "Shrug", category = "Gesture", loop = 0},
    {dic = "missexile1_cargoplane", anim = "call_radio_player2", label = "Siediti e parla alla radio", category = "Misc", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_what_hard", label = "Cosa?", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_why", label = "Perché?", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_nod_yes_hard", label = "Si", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_you_hard", label = "Tu", category = "Gesture", loop = 0},
    {dic = "anim@amb@business@coc@coc_packing_hi@", anim = "full_cycle_v1_pressoperator", label = "Operare Presso", category = "Misc", loop = 0},
    {dic = "missfam5_blackout", anim = "pass_out", label = "Svenire", category = "Misc", loop = 0},
    {dic = "missfbi5ig_21", anim = "holdup_hallway_saw_player_scientist", label = "Spaventato", category = "Misc", loop = 0},
    {dic = "missfbi5ig_21", anim = "hand_up_scientist", label = "Mani in alto (scienziato)", category = "Misc", loop = 0},
    {dic = "missfbi5ig_36", anim = "_reaction_to_heli", label = "Guarda elicottero", category = "Misc", loop = 0},
    {dic = "missheist_agency3astumble_getup", anim = "stumble_getup", label = "Stumble Get Up", category = "Misc", loop = 0},
    {dic = "missfam5_blackout", anim = "vomit", label = "Vomito", category = "Misc", loop = 0},
    {dic = "missfam5_yoga", anim = "f_yogapose_a", label = "Posa di yoga ", category = "Misc", loop = 0},
	{dic = "mp_ped_interaction", anim = "hugs_guy_a", label = "Abbraccio", category = "New", loop = 0},
	{dic = "mp_player_int_upperwank", anim = "mp_player_int_wank_01", label = "Segarsi", category = "New", loop = 0},
	{dic = "mp_arresting", anim = "idle", label = "Ammanettato", category = "New", loop = 0},
	{dic = "anim@mp_snowball", anim = "pickup_snowball", label = "Raccogliere", category = "New", loop = 0},
	{dic = "anim@mp_player_intuppernose_pick", anim = "enter", label = "Scaccolati", category = "New", loop = 0},
	{dic = "mini@prostitutes@sexnorm_veh", anim = "bj_loop_prostitute", label = "BJ Giver", category = "New", loop = 0},
	{dic = "mini@prostitutes@sexnorm_veh", anim = "bj_loop_male", label = "BJ Getter", category = "New", loop = 0},

	{dic = "rcmpaparazzo_2", anim = "shag_loop_poppy", label = "Sex Getter", category = "New", loop = 0},
	{dic = "rcmpaparazzo_2", anim = "shag_loop_a", label = "Prostituta", category = "New", loop = 0},

	{dic = "mini@prostitutes@sexnorm_veh", anim = "sex_loop_male", label = "Veh Sex Getter", category = "New", loop = 0},
	{dic = "veh@low@front_ps@enter_exit", anim = "d_locked", label = "Veh Sex Giver", category = "New", loop = 0},
}

walkanims = {
	{dic = "amb@world_human_hang_out_street@female_arms_crossed@idle_a", anim = "idle_a", label = "Braccia incrociate"},
	{dic = "misscarsteal4@actor", anim = "actor_berating_assistant", label = "Rimproverando"},
	{dic = "amb@incar@male@smoking_van@idle_a", anim = "idle_a", label = "Fumare in auto"},
	{dic = "amb@world_human_smoking_pot@male@idle_a", anim = "idle_c", label = "Fumare 2"},
	{dic = "mp_player_int_uppergang_sign_b", anim = "mp_player_int_gang_sign_b_exit", label = "Gang"},
	{dic = "amb@code_human_in_car_mp_actions@gang_sign_b@std@ds@base", anim = "idle_a", label = "Gang2"},
	{dic = "amb@code_human_in_car_mp_actions@gang_sign_a@bodhi@rds@base", anim = "idle_a", label = "Gang3"},
		
}


scens = {
    {scen = "PROP_HUMAN_SEAT_ARMCHAIR", label = "Poltrona", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.55, -180}}},
    {scen = "WORLD_HUMAN_GUARD_STAND_ARMY", label = "Esercito in piedi", category = "Jobs"},
    {scen = "PROP_HUMAN_ATM", label = "ATM", category = "Misc"},
    {scen = "PROP_HUMAN_SEAT_BAR", label = "Sgabello bar", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.0, -0.3, 0}, ["mp_f_freemode_01"] = {0.0, 0.0, -0.2, 0}}},
    {scen = "PROP_HUMAN_BBQ", label = "BBQ", category = "Hobby"},
    {scen = "PROP_HUMAN_SEAT_BENCH", label = "Panca", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_BENCH_DRINK", label = "Bevanda da banco", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_BENCH_DRINK_BEER", label = "Birra da banco", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_BENCH_FOOD", label = "Sedersi in panchina per mangiare", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS", label = "Panca", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS_PRISON", label = "Panca (Prigione)", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "WORLD_HUMAN_BINOCULARS", label = "Binocolo", category = "Misc"},
    {scen = "WORLD_HUMAN_WINDOW_SHOP_BROWSE", label = "Browse Shop Window", category = "Misc"},
    {scen = "PROP_HUMAN_SEAT_BUS_STOP_WAIT", label = "Fermata Autobus", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "WORLD_HUMAN_CAR_PARK_ATTENDANT", label = "Addetto al parcheggio", category = "Jobs"},
    {scen = "PROP_HUMAN_SEAT_CHAIR", label = "Sedia", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_CHAIR_DRINK", label = "Sedersi e bere", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_CHAIR_DRINK_BEER", label = "Sedersi bevendo birra", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_CHAIR_FOOD", label = "Sedersi mangiando", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_CHAIR_MP_PLAYER", label = "Sedia", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "WORLD_HUMAN_CHEERING", label = "Applauso", category = "Misc"},
    {scen = "WORLD_HUMAN_CLIPBOARD", label = "Appunti", category = "Jobs"},
    {scen = "WORLD_HUMAN_AA_COFFEE", label = "Caffè", category = "Drink"},
    {scen = "CODE_HUMAN_POLICE_CROWD_CONTROL", label = "Controllo della folla", category = "EMS"},
    {scen = "PROP_HUMAN_SEAT_DECKCHAIR", label = "Sdraio", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_DECKCHAIR_DRINK", label = "Sdraiarsi e bere", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "WORLD_HUMAN_CONST_DRILL", label = "Perforazione", category = "Jobs"},
    {scen = "WORLD_HUMAN_DRINKING", label = "Bere", category = "Drink"},
    {scen = "WORLD_HUMAN_DRUG_DEALER", label = "Spacciatore", category = "Jobs"},
    {scen = "WORLD_HUMAN_DRUG_DEALER_HARD", label = "Drug Dealer Hard", category = "Jobs"},
    {scen = "WORLD_HUMAN_MOBILE_FILM_SHOCKING", label = "Film con il telefono", category = "Misc"},
    {scen = "WORLD_HUMAN_STAND_FISHING", label = "Pesca", category = "Jobs"},
    {scen = "WORLD_HUMAN_MUSCLE_FLEX", label = "Flettere", category = "Hobby"},
    {scen = "WORLD_HUMAN_BUM_FREEWAY", label = "Freeway Bum", category = "Misc"},
    {scen = "WORLD_HUMAN_GUARD_PATROL", label = "Guardia Patrol", category = "Jobs"},
    {scen = "WORLD_HUMAN_GUARD_STAND", label = "Guardia in piedi", category = "Jobs"},
    {scen = "WORLD_HUMAN_HAMMERING", label = "Martellamento", category = "Jobs"},
    {scen = "WORLD_HUMAN_HANG_OUT_STREET", label = "Passare il tempo", category = "Misc"},
    {scen = "WORLD_HUMAN_PROSTITUTE_LOW_CLASS", label = "Prostituta di alta classe", category = "Jobs"},
    {scen = "WORLD_HUMAN_HIKER_STANDING", label = "Escursionista in piedi", category = "Misc"},
    {scen = "WORLD_HUMAN_HUMAN_STATUE", label = "Statua umana", category = "Jobs"},
    {scen = "WORLD_HUMAN_COP_IDLES", label = "Poliziotto inattivo", category = "Jobs"},
    {scen = "WORLD_HUMAN_STAND_IMPATIENT", label = "Impaziente", category = "Misc"},
    {scen = "WORLD_HUMAN_JANITOR", label = "Bidella/o", category = "Jobs"},
    {scen = "WORLD_HUMAN_JOG_STANDING", label = "Jog On The Spot", category = "Misc"},
    {scen = "WORLD_HUMAN_GARDENER_LEAF_BLOWER", label = "Tagliaerba", category = "Jobs"},
    {scen = "WORLD_HUMAN_LEANING", label = "Pendente", category = "Misc"},
    {scen = "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS", label = "Prostituta di basso livello", category = "Jobs"},
    {scen = "WORLD_HUMAN_VEHICLE_MECHANIC", label = "Meccanico", category = "Jobs"},
    {scen = "PROP_HUMAN_BUM_BIN", label = "Meccanico 2", category = "Jobs"},
    {scen = "CODE_HUMAN_MEDIC_KNEEL", label = "Medic Kneel", category = "EMS"},
    {scen = "CODE_HUMAN_MEDIC_TIME_OF_DEATH", label = "Medic Time Of Death", category = "EMS"},
    {scen = "WORLD_HUMAN_TOURIST_MOBILE", label = "Mobile", category = "Misc"},
    {scen = "WORLD_HUMAN_MUSICIAN", label = "Musicista", category = "Jobs"},
    {scen = "WORLD_HUMAN_PAPARAZZI", label = "Paparazzi", category = "Jobs"},
    {scen = "WORLD_HUMAN_PARTYING", label = "Festeggiare", category = "Hobby"},
    {scen = "WORLD_HUMAN_PICNIC", label = "Picnic", category = "Hobby"},
    {scen = "WORLD_HUMAN_GARDENER_PLANT", label = "Piantare", category = "Jobs"},
    {scen = "CODE_HUMAN_POLICE_INVESTIGATE", label = "Investigare polizia", category = "EMS"},
    {scen = "WORLD_HUMAN_PUSH_UPS", label = "Sollevamento", category = "Hobby"},
    {scen = "PROP_HUMAN_SEAT_COMPUTER", label = "Sedersi al computer", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_CHAIR_UPRIGHT", label = "Sat Upright", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_SEWING", label = "Cucire", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "WORLD_HUMAN_SECURITY_SHINE_TORCH", label = "Torcia di sicurezza", category = "Jobs"},
    {scen = "WORLD_HUMAN_SIT_UPS", label = "Sit Ups", category = "Hobby"},
    {scen = "WORLD_HUMAN_BUM_SLUMPED", label = "Accasciato", category = "Misc"},
    {scen = "WORLD_HUMAN_STAND_FIRE", label = "Stand By Fire", category = "Misc"},
    {scen = "WORLD_HUMAN_STAND_MOBILE", label = "Stand Using Mobile", category = "Misc"},
    {scen = "WORLD_HUMAN_BUM_STANDING", label = "Standing Bum", category = "Misc"},
    {scen = "WORLD_HUMAN_STUPOR", label = "Stupore", category = "Drink"},
    {scen = "WORLD_HUMAN_SUNBATHE", label = "Prendere il sole", category = "Hobby"},
    {scen = "WORLD_HUMAN_SUNBATHE_BACK", label = "Prendere il sole sulla schiena", category = "Hobby"},
    {scen = "PROP_HUMAN_SEAT_SUNLOUNGER", label = "Lettino", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.8, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.9, -0.5, -180}}},
    {scen = "WORLD_HUMAN_SUPERHERO", label = "Supereroe", category = "Hobby"},
    {scen = "WORLD_HUMAN_SWIMMING", label = "Nuotare", category = "Hobby"},
    {scen = "CODE_HUMAN_MEDIC_TEND_TO_DEAD", label = "Tend To Dead", category = "EMS"},
    {scen = "WORLD_HUMAN_TENNIS_PLAYER", label = "Giocatore di tennis", category = "Hobby"},
    {scen = "WORLD_HUMAN_TOURIST_MAP", label = "Turista con la mappa", category = "Misc"},
    {scen = "WORLD_HUMAN_BUM_WASH", label = "Washing Bum", category = "Misc"},
    {scen = "WORLD_HUMAN_STRIP_WATCH_STAND", label = "Guarda Stripper", category = "Hobby"},
    {scen = "WORLD_HUMAN_MUSCLE_FREE_WEIGHTS", label = "Pesi", category = "Hobby"},
    {scen = "WORLD_HUMAN_WELDING", label = "Saldatura", category = "Jobs"},
    {scen = "WORLD_HUMAN_YOGA", label = "Yoga", category = "Hobby"},
}

walks = {
    {Walk = "move_m@shadyped@a", label = "Gangsta", category = "Walking"},    
    {Walk = "move_m@muscle@a", label = "Depressa/o", category = "Walking"},
    {Walk = "move_m@business@a", label = "Business", category = "Walking"},
    {Walk = "move_m@gangster@var_e", label = "Lento", category = "Walking"},
    {Walk = "move_characters@franklin@fire", label = "Fuoco", category = "Walking"},
    {Walk = "move_m@drunk@moderatedrunk", label = "Ubriaco", category = "Walking"},
    {Walk = "move_m@brave@a", label = "Determinare", category = "Walking"},
    {Walk = "move_m@hipster@a", label = "Fricchettone/a", category = "Walking"},
    {Walk = "move_m@muscle@a", label = "Muscolo", category = "Walking"},
    {Walk = "move_m@fat@a", label = "Ombreggiata/o", category = "Walking"},
    {Walk = "move_f@sassy", label = "Insolente", category = "Walking"},
    {Walk = "move_m@injured", label = "Ferito/o", category = "Walking"},
    {Walk = "move_m@money", label = "Orgoglioso/a", category = "Walking"},
    {Walk = "move_f@arrogant@a", label = "Arrogante", category = "Walking"},
    {Walk = "move_m@swagger@b", label = "Swag", category = "Walking"},
    {Walk = "move_m@swagger", label = "Swag2", category = "Walking"},
}
