anims = {
    {dic = "gestures@f@standing@casual", anim = "gesture_bring_it_on", label = "Bring It On", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_bye_hard", label = "Bye", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_come_here_hard", label = "Come Here", category = "Gesture", loop = 0},
    {dic = "missheist_agency3aig_24", anim = "agent01_conversation", label = "Conversation", category = "Misc", loop = 0},
    {dic = "misscarstealfinalecar_5_ig_3", anim = "crouchloop", label = "Crouch Hide", category = "Misc", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_damn", label = "Damn", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_displeased", label = "Displeased", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_easy_now", label = "Easy Now", category = "Gesture", loop = 0},
	{dic = "mp_sleep", anim = "sleep_introfemale", label = "Fall asleep", category = "Misc", loop = 50},
    {dic = "gestures@f@standing@casual", anim = "gesture_hello", label = "Hello", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "getsure_its_mine", label = "It's Mine", category = "Gesture", loop = 0},
    {dic = "missfam4leadinoutmcs2", anim = "tracy_loop", label = "Kneel On Ground Upset", category = "Misc", loop = 0},
    {dic = "mp_safehouse", anim = "lap_dance_girl", label = "Lap Dance", category = "Misc", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_me", label = "Me", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_head_no", label = "No", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_no_way", label = "No Way", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_pleased", label = "Pleased", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_point", label = "Point", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_shrug_hard", label = "Shrug", category = "Gesture", loop = 0},
    {dic = "missexile1_cargoplane", anim = "call_radio_player2", label = "Sit And Talk On Radio", category = "Misc", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_what_hard", label = "What", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_why", label = "Why", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_nod_yes_hard", label = "Yes", category = "Gesture", loop = 0},
    {dic = "gestures@f@standing@casual", anim = "gesture_you_hard", label = "You", category = "Gesture", loop = 0},
    {dic = "anim@amb@business@coc@coc_packing_hi@", anim = "full_cycle_v1_pressoperator", label = "Operate Press", category = "Misc", loop = 0},
    {dic = "missfam5_blackout", anim = "pass_out", label = "Pass Out", category = "Misc", loop = 0},
    {dic = "missfbi5ig_21", anim = "holdup_hallway_saw_player_scientist", label = "Scared", category = "Misc", loop = 0},
    {dic = "missfbi5ig_21", anim = "hand_up_scientist", label = "Scienist Hands Up", category = "Misc", loop = 0},
    {dic = "missfbi5ig_36", anim = "_reaction_to_heli", label = "See Heli", category = "Misc", loop = 0},
    {dic = "missheist_agency3astumble_getup", anim = "stumble_getup", label = "Stumble Get Up", category = "Misc", loop = 0},
    {dic = "missfam5_blackout", anim = "vomit", label = "Vomit", category = "Misc", loop = 0},
    {dic = "missfam5_yoga", anim = "f_yogapose_a", label = "Yoga Pose", category = "Misc", loop = 0},
	{dic = "mp_ped_interaction", anim = "hugs_guy_a", label = "Hug", category = "New", loop = 0},
	{dic = "mp_player_int_upperwank", anim = "mp_player_int_wank_01", label = "Wanker", category = "New", loop = 0},
	{dic = "mp_arresting", anim = "idle", label = "Hancuffed", category = "New", loop = 0},
	{dic = "anim@mp_snowball", anim = "pickup_snowball", label = "Pickup", category = "New", loop = 0},
	{dic = "anim@mp_player_intuppernose_pick", anim = "enter", label = "Pick Nose", category = "New", loop = 0},
	{dic = "mini@prostitutes@sexnorm_veh", anim = "bj_loop_prostitute", label = "BJ Giver", category = "New", loop = 0},
	{dic = "mini@prostitutes@sexnorm_veh", anim = "bj_loop_male", label = "BJ Getter", category = "New", loop = 0},

	{dic = "rcmpaparazzo_2", anim = "shag_loop_poppy", label = "Sex Getter", category = "New", loop = 0},
	{dic = "rcmpaparazzo_2", anim = "shag_loop_a", label = "Sex Giver", category = "New", loop = 0},

	{dic = "mini@prostitutes@sexnorm_veh", anim = "sex_loop_male", label = "Veh Sex Getter", category = "New", loop = 0},
	{dic = "veh@low@front_ps@enter_exit", anim = "d_locked", label = "Veh Sex Giver", category = "New", loop = 0},
}

walkanims = {
	{dic = "amb@world_human_hang_out_street@female_arms_crossed@idle_a", anim = "idle_a", label = "Arms Crossed"},
	{dic = "misscarsteal4@actor", anim = "actor_berating_assistant", label = "Berating"},
	{dic = "amb@incar@male@smoking_van@idle_a", anim = "idle_a", label = "Smoking In-car"},
	{dic = "amb@world_human_smoking_pot@male@idle_a", anim = "idle_c", label = "Smoking 2"},
	{dic = "mp_player_int_uppergang_sign_b", anim = "mp_player_int_gang_sign_b_exit", label = "Gang"},
	{dic = "amb@code_human_in_car_mp_actions@gang_sign_b@std@ds@base", anim = "idle_a", label = "Gang2"},
	{dic = "amb@code_human_in_car_mp_actions@gang_sign_a@bodhi@rds@base", anim = "idle_a", label = "Gang3"},
		
}


scens = {
    {scen = "PROP_HUMAN_SEAT_ARMCHAIR", label = "Armchair", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.55, -180}}},
    {scen = "WORLD_HUMAN_GUARD_STAND_ARMY", label = "Army Standing", category = "Jobs"},
    {scen = "PROP_HUMAN_ATM", label = "ATM", category = "Misc"},
    {scen = "PROP_HUMAN_SEAT_BAR", label = "Bar Seat", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.0, -0.3, 0}, ["mp_f_freemode_01"] = {0.0, 0.0, -0.2, 0}}},
    {scen = "PROP_HUMAN_BBQ", label = "BBQ", category = "Hobby"},
    {scen = "PROP_HUMAN_SEAT_BENCH", label = "Bench", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_BENCH_DRINK", label = "Bench Drink", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_BENCH_DRINK_BEER", label = "Bench Drink Beer", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_BENCH_FOOD", label = "Bench Eating", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS", label = "Bench Press", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS_PRISON", label = "Bench Press (Prison)", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "WORLD_HUMAN_BINOCULARS", label = "Binoculars", category = "Misc"},
    {scen = "WORLD_HUMAN_WINDOW_SHOP_BROWSE", label = "Browse Shop Window", category = "Misc"},
    {scen = "PROP_HUMAN_SEAT_BUS_STOP_WAIT", label = "Bus Stop", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "WORLD_HUMAN_CAR_PARK_ATTENDANT", label = "Car Park Attendant", category = "Jobs"},
    {scen = "PROP_HUMAN_SEAT_CHAIR", label = "Chair", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_CHAIR_DRINK", label = "Chair Drinking", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_CHAIR_DRINK_BEER", label = "Chair Drinking Beer", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_CHAIR_FOOD", label = "Chair Eating", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_CHAIR_MP_PLAYER", label = "Chair (MP Char)", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "WORLD_HUMAN_CHEERING", label = "Cheering", category = "Misc"},
    {scen = "WORLD_HUMAN_CLIPBOARD", label = "Clipboard", category = "Jobs"},
    {scen = "WORLD_HUMAN_AA_COFFEE", label = "Coffee", category = "Drink"},
    {scen = "CODE_HUMAN_POLICE_CROWD_CONTROL", label = "Crowd Control", category = "EMS"},
    {scen = "PROP_HUMAN_SEAT_DECKCHAIR", label = "Deckchair", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_DECKCHAIR_DRINK", label = "Deckchair Drinking", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "WORLD_HUMAN_CONST_DRILL", label = "Drilling", category = "Jobs"},
    {scen = "WORLD_HUMAN_DRINKING", label = "Drinking", category = "Drink"},
    {scen = "WORLD_HUMAN_DRUG_DEALER", label = "Drug Dealer", category = "Jobs"},
    {scen = "WORLD_HUMAN_DRUG_DEALER_HARD", label = "Drug Dealer Hard", category = "Jobs"},
    {scen = "WORLD_HUMAN_MOBILE_FILM_SHOCKING", label = "Film With Phone", category = "Misc"},
    {scen = "WORLD_HUMAN_STAND_FISHING", label = "Fishing", category = "Jobs"},
    {scen = "WORLD_HUMAN_MUSCLE_FLEX", label = "Flex", category = "Hobby"},
    {scen = "WORLD_HUMAN_BUM_FREEWAY", label = "Freeway Bum", category = "Misc"},
    {scen = "WORLD_HUMAN_GUARD_PATROL", label = "Guard Patrol", category = "Jobs"},
    {scen = "WORLD_HUMAN_GUARD_STAND", label = "Guard Standing", category = "Jobs"},
    {scen = "WORLD_HUMAN_HAMMERING", label = "Hammering", category = "Jobs"},
    {scen = "WORLD_HUMAN_HANG_OUT_STREET", label = "Hang Out", category = "Misc"},
    {scen = "WORLD_HUMAN_PROSTITUTE_LOW_CLASS", label = "High Class Prostitute", category = "Jobs"},
    {scen = "WORLD_HUMAN_HIKER_STANDING", label = "Hiker Standing", category = "Misc"},
    {scen = "WORLD_HUMAN_HUMAN_STATUE", label = "Human Statue", category = "Jobs"},
    {scen = "WORLD_HUMAN_COP_IDLES", label = "Idling Cop", category = "Jobs"},
    {scen = "WORLD_HUMAN_STAND_IMPATIENT", label = "Impatient", category = "Misc"},
    {scen = "WORLD_HUMAN_JANITOR", label = "Janitor", category = "Jobs"},
    {scen = "WORLD_HUMAN_JOG_STANDING", label = "Jog On The Spot", category = "Misc"},
    {scen = "WORLD_HUMAN_GARDENER_LEAF_BLOWER", label = "Leaf Blower", category = "Jobs"},
    {scen = "WORLD_HUMAN_LEANING", label = "Lean", category = "Misc"},
    {scen = "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS", label = "Low Class Prostitute", category = "Jobs"},
    {scen = "WORLD_HUMAN_VEHICLE_MECHANIC", label = "Mechanic", category = "Jobs"},
    {scen = "PROP_HUMAN_BUM_BIN", label = "Mechanic 2", category = "Jobs"},
    {scen = "CODE_HUMAN_MEDIC_KNEEL", label = "Medic Kneel", category = "EMS"},
    {scen = "CODE_HUMAN_MEDIC_TIME_OF_DEATH", label = "Medic Time Of Death", category = "EMS"},
    {scen = "WORLD_HUMAN_TOURIST_MOBILE", label = "Mobile", category = "Misc"},
    {scen = "WORLD_HUMAN_MUSICIAN", label = "Musician", category = "Jobs"},
    {scen = "WORLD_HUMAN_PAPARAZZI", label = "Paparazzi", category = "Jobs"},
    {scen = "WORLD_HUMAN_PARTYING", label = "Partying", category = "Hobby"},
    {scen = "WORLD_HUMAN_PICNIC", label = "Picnic", category = "Hobby"},
    {scen = "WORLD_HUMAN_GARDENER_PLANT", label = "Planting", category = "Jobs"},
    {scen = "CODE_HUMAN_POLICE_INVESTIGATE", label = "Police Investigate", category = "EMS"},
    {scen = "WORLD_HUMAN_PUSH_UPS", label = "Push Ups", category = "Hobby"},
    {scen = "PROP_HUMAN_SEAT_COMPUTER", label = "Sat At Computer", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_CHAIR_UPRIGHT", label = "Sat Upright", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "PROP_HUMAN_SEAT_SEWING", label = "Sewing", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.6, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.7, -0.5, -180}}},
    {scen = "WORLD_HUMAN_SECURITY_SHINE_TORCH", label = "Shine Torch", category = "Jobs"},
    {scen = "WORLD_HUMAN_SIT_UPS", label = "Sit Ups", category = "Hobby"},
    {scen = "WORLD_HUMAN_BUM_SLUMPED", label = "Slumped", category = "Misc"},
    {scen = "WORLD_HUMAN_STAND_FIRE", label = "Stand By Fire", category = "Misc"},
    {scen = "WORLD_HUMAN_STAND_MOBILE", label = "Stand Using Mobile", category = "Misc"},
    {scen = "WORLD_HUMAN_BUM_STANDING", label = "Standing Bum", category = "Misc"},
    {scen = "WORLD_HUMAN_STUPOR", label = "Stupor", category = "Drink"},
    {scen = "WORLD_HUMAN_SUNBATHE", label = "Sunbathe", category = "Hobby"},
    {scen = "WORLD_HUMAN_SUNBATHE_BACK", label = "Sunbathe On Back", category = "Hobby"},
    {scen = "PROP_HUMAN_SEAT_SUNLOUNGER", label = "Sunlounger", category = "Sat", pos = {["mp_m_freemode_01"] = {0.0, 0.8, -0.5, -180}, ["mp_f_freemode_01"] = {0.0, 0.9, -0.5, -180}}},
    {scen = "WORLD_HUMAN_SUPERHERO", label = "Superhero", category = "Hobby"},
    {scen = "WORLD_HUMAN_SWIMMING", label = "Swimming", category = "Hobby"},
    {scen = "CODE_HUMAN_MEDIC_TEND_TO_DEAD", label = "Tend To Dead", category = "EMS"},
    {scen = "WORLD_HUMAN_TENNIS_PLAYER", label = "Tennis Player", category = "Hobby"},
    {scen = "WORLD_HUMAN_TOURIST_MAP", label = "Tourist With Map", category = "Misc"},
    {scen = "WORLD_HUMAN_BUM_WASH", label = "Washing Bum", category = "Misc"},
    {scen = "WORLD_HUMAN_STRIP_WATCH_STAND", label = "Watch Stripper", category = "Hobby"},
    {scen = "WORLD_HUMAN_MUSCLE_FREE_WEIGHTS", label = "Weights", category = "Hobby"},
    {scen = "WORLD_HUMAN_WELDING", label = "Welding", category = "Jobs"},
    {scen = "WORLD_HUMAN_YOGA", label = "Yoga", category = "Hobby"},
}

walks = {
    {Walk = "move_m@shadyped@a", label = "Gangsta", category = "Walking"},    
    {Walk = "move_m@muscle@a", label = "Depressed", category = "Walking"},
    {Walk = "move_m@business@a", label = "Business", category = "Walking"},
    {Walk = "move_m@gangster@var_e", label = "Slow", category = "Walking"},
    {Walk = "move_characters@franklin@fire", label = "Fire", category = "Walking"},
    {Walk = "move_m@drunk@moderatedrunk", label = "Drunk", category = "Walking"},
    {Walk = "move_m@brave@a", label = "Determine", category = "Walking"},
    {Walk = "move_m@hipster@a", label = "Hipster", category = "Walking"},
    {Walk = "move_m@muscle@a", label = "Muscle", category = "Walking"},
    {Walk = "move_m@fat@a", label = "Shady", category = "Walking"},
    {Walk = "move_f@sassy", label = "Sassy", category = "Walking"},
    {Walk = "move_m@injured", label = "Injured", category = "Walking"},
    {Walk = "move_m@money", label = "Proud", category = "Walking"},
    {Walk = "move_f@arrogant@a", label = "Arrogant", category = "Walking"},
    {Walk = "move_m@swagger@b", label = "Swag", category = "Walking"},
    {Walk = "move_m@swagger", label = "Swag2", category = "Walking"},
}
