Config = {}

Config.Animations = {

	{
		name  = 'festives',
		label = 'Festivo',
		items = {
			{label = "Fumare una sigaretta", type = "scenario", data = {anim = "WORLD_HUMAN_SMOKING"}},
			{label = "Suonare la musica", type = "scenario", data = {anim = "WORLD_HUMAN_MUSICIAN"}},
			{label = "Dj", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@dj", anim = "dj"}},
			{label = "Bere una birra", type = "scenario", data = {anim = "WORLD_HUMAN_DRINKING"}},
			{label = "Bere una birra", type = "scenario", data = {anim = "WORLD_HUMAN_PARTYING"}},
			{label = "Fingere di suonare la chitarra", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@air_guitar", anim = "air_guitar"}},
			{label = "Ballare", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@air_shagging", anim = "air_shagging"}},
			{label = "Rock'n'roll", type = "anim", data = {lib = "mp_player_int_upperrock", anim = "mp_player_int_rock"}},
			{label = "Fumare una canna", type = "scenario", data = {anim = "WORLD_HUMAN_SMOKING_POT"}},
			{label = "ballare sul posto", type = "anim", data = {lib = "amb@world_human_bum_standing@drunk@idle_a", anim = "idle_a"}},
			{label = "Vomitare dalla macchina", type = "anim", data = {lib = "oddjobs@taxi@tie", anim = "vomit_outside"}},
		}
	},

	{
		name  = 'greetings',
		label = 'Saluti',
		items = {
			{label = "Ciao", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_hello"}},
			{label = "Stretta di mano", type = "anim", data = {lib = "mp_common", anim = "givetake1_a"}},
			{label = "Saluto normale", type = "anim", data = {lib = "mp_ped_interaction", anim = "handshake_guy_a"}},
			{label = "Stretta di mano con abbraccio", type = "anim", data = {lib = "mp_ped_interaction", anim = "hugs_guy_a"}},
			{label = "Saluto Militare", type = "anim", data = {lib = "mp_player_int_uppersalute", anim = "mp_player_int_salute"}},
		}
	},

	{
		name  = 'work',
		label = 'Azioni lavoro',
		items = {
			{label = "Sospetto : arrendersi alla polizia", type = "anim", data = {lib = "random@arrests@busted", anim = "idle_c"}},
			{label = "Pescare", type = "scenario", data = {anim = "world_human_stand_fishing"}},
			{label = "Polizia : osservare", type = "anim", data = {lib = "amb@code_human_police_investigate@idle_b", anim = "idle_f"}},
			{label = "Polizia : parlare in radio", type = "anim", data = {lib = "random@arrests", anim = "generic_radio_chatter"}},
			{label = "Polizia : circolazione", type = "scenario", data = {anim = "WORLD_HUMAN_CAR_PARK_ATTENDANT"}},
			{label = "Police : binocolo", type = "scenario", data = {anim = "WORLD_HUMAN_BINOCULARS"}},
			{label = "Agricoltore : raccogliere", type = "scenario", data = {anim = "world_human_gardener_plant"}},
			{label = "Meccanico : riparare il motore", type = "anim", data = {lib = "mini@repair", anim = "fixing_a_ped"}},
			{label = "Medico : osservare il ferito", type = "scenario", data = {anim = "CODE_HUMAN_MEDIC_KNEEL"}},
			{label = "Taxi : parlare al cliente", type = "anim", data = {lib = "oddjobs@taxi@driver", anim = "leanover_idle"}},
			{label = "Taxi : fai la fattura", type = "anim", data = {lib = "oddjobs@taxi@cyi", anim = "std_hand_off_ps_passenger"}},
			{label = "Spacciatore : consegna pacco", type = "anim", data = {lib = "mp_am_hold_up", anim = "purchase_beerbox_shopkeeper"}},
			{label = "Barman : servi uno shottino", type = "anim", data = {lib = "mini@drinking", anim = "shots_barman_b"}},
			{label = "Fotografo : fai una fotografia", type = "scenario", data = {anim = "WORLD_HUMAN_PAPARAZZI"}},
			{label = "Prendere nota", type = "scenario", data = {anim = "WORLD_HUMAN_CLIPBOARD"}},
			{label = "Mettere un chiodo", type = "scenario", data = {anim = "WORLD_HUMAN_HAMMERING"}},
			{label = "Clochard : Chiedere l'elemosina", type = "scenario", data = {anim = "WORLD_HUMAN_BUM_FREEWAY"}},
			{label = "Clochard : Fai la statua", type = "scenario", data = {anim = "WORLD_HUMAN_HUMAN_STATUE"}},
		}
	},

	{
		name  = 'humors',
		label = 'Umore',
		items = {
			{label = "Applauso", type = "scenario", data = {anim = "WORLD_HUMAN_CHEERING"}},
			{label = "Pollice in su", type = "anim", data = {lib = "mp_action", anim = "thanks_male_06"}},
			{label = "Indicare", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_point"}},
			{label = "Vieni", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_come_here_soft"}}, 
			{label = "Allarga le braccia", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_bring_it_on"}},
			{label = "A me", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_me"}},
			{label = "Lo sapevo, cazzo!", type = "anim", data = {lib = "anim@am_hold_up@male", anim = "shoplift_high"}},
			{label = "Sono in una brutta situazione", type = "scenario", data = {lib = "amb@world_human_bum_standing@depressed@idle_a", anim = "idle_a"}},
			{label = "Ma guarda tu sto coglione", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@face_palm", anim = "face_palm"}},
			{label = "Calmati ", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_easy_now"}},
			{label = "Cosa ho fatto ?", type = "anim", data = {lib = "oddjobs@assassinate@multi@", anim = "react_big_variations_a"}},
			{label = "Impaurito", type = "anim", data = {lib = "amb@code_human_cower_stand@male@react_cowering", anim = "base_right"}},
			{label = "Lotta ?", type = "anim", data = {lib = "anim@deathmatch_intros@unarmed", anim = "intro_male_unarmed_e"}},
			{label = "Non è possibile !", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_damn"}},
			{label = "Abbracciare", type = "anim", data = {lib = "mp_ped_interaction", anim = "kisses_guy_a"}},
			{label = "Fanculo", type = "anim", data = {lib = "mp_player_int_upperfinger", anim = "mp_player_int_finger_01_enter"}},
			{label = "Madturbarsi", type = "anim", data = {lib = "mp_player_int_upperwank", anim = "mp_player_int_wank_01"}},
			{label = "Fingere di spararsi alla testa", type = "anim", data = {lib = "mp_suicide", anim = "pistol"}},
		}
	},

	{
		name  = 'sports',
		label = 'Sport',
		items = {
			{label = "Mostrare i muscoli", type = "anim", data = {lib = "amb@world_human_muscle_flex@arms_at_side@base", anim = "base"}},
			{label = "Bicipiti", type = "anim", data = {lib = "amb@world_human_muscle_free_weights@male@barbell@base", anim = "base"}},
			{label = "Flessioni", type = "anim", data = {lib = "amb@world_human_push_ups@male@base", anim = "base"}},
			{label = "Addominali", type = "anim", data = {lib = "amb@world_human_sit_ups@male@base", anim = "base"}},
			{label = "yoga", type = "anim", data = {lib = "amb@world_human_yoga@male@base", anim = "base_a"}},
		}
	},

	{
		name  = 'misc',
		label = 'Diverse',
		items = {
			{label = "Bere un cafè", type = "anim", data = {lib = "amb@world_human_aa_coffee@idle_a", anim = "idle_a"}},
			{label = "Sedersi", type = "anim", data = {lib = "anim@heists@prison_heistunfinished_biztarget_idle", anim = "target_idle"}},
			{label = "Attendere contro il muro", type = "scenario", data = {anim = "world_human_leaning"}},
			{label = "Sdraiato sulla schiena", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE_BACK"}},
			{label = "Sdraiato sul ventre", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE"}},
			{label = "Pulire qualcosa", type = "scenario", data = {anim = "world_human_maid_clean"}},
			{label = "Cucinare", type = "scenario", data = {anim = "PROP_HUMAN_BBQ"}},
			{label = "Posizione follie", type = "anim", data = {lib = "mini@prostitutes@sexlow_veh", anim = "low_car_bj_to_prop_female"}},
			{label = "Farsi un selfie", type = "scenario", data = {anim = "world_human_tourist_mobile"}},
			{label = "Ascoltare da una porta", type = "anim", data = {lib = "mini@safe_cracking", anim = "idle_base"}}, 
		}
	},

	{
		name  = 'attitudem',
		label = 'Atteggiamenti',
		items = {
			{label = "Normale M", type = "attitude", data = {lib = "move_m@confident", anim = "move_m@confident"}},
			{label = "Normale F", type = "attitude", data = {lib = "move_f@heels@c", anim = "move_f@heels@c"}},
			{label = "Depressivo M", type = "attitude", data = {lib = "move_m@depressed@a", anim = "move_m@depressed@a"}},
			{label = "Depressivo F", type = "attitude", data = {lib = "move_f@depressed@a", anim = "move_f@depressed@a"}},
			{label = "Affari", type = "attitude", data = {lib = "move_m@business@a", anim = "move_m@business@a"}},
			{label = "Determinato", type = "attitude", data = {lib = "move_m@brave@a", anim = "move_m@brave@a"}},
			{label = "Casuale", type = "attitude", data = {lib = "move_m@casual@a", anim = "move_m@casual@a"}},
			{label = "Appesantito", type = "attitude", data = {lib = "move_m@fat@a", anim = "move_m@fat@a"}},
			{label = "Coatto", type = "attitude", data = {lib = "move_m@hipster@a", anim = "move_m@hipster@a"}},
			{label = "Ferito", type = "attitude", data = {lib = "move_m@injured", anim = "move_m@injured"}},
			{label = "Nervoso", type = "attitude", data = {lib = "move_m@hurry@a", anim = "move_m@hurry@a"}},
			{label = "Vagabondo", type = "attitude", data = {lib = "move_m@hobo@a", anim = "move_m@hobo@a"}},
			{label = "Infelice", type = "attitude", data = {lib = "move_m@sad@a", anim = "move_m@sad@a"}},
			{label = "Muscoloso", type = "attitude", data = {lib = "move_m@muscle@a", anim = "move_m@muscle@a"}},
			{label = "Shockato", type = "attitude", data = {lib = "move_m@shocked@a", anim = "move_m@shocked@a"}},
			{label = "Sicuro", type = "attitude", data = {lib = "move_m@shadyped@a", anim = "move_m@shadyped@a"}},
			{label = "Stressato", type = "attitude", data = {lib = "move_m@buzzed", anim = "move_m@buzzed"}},
			{label = "Pressato", type = "attitude", data = {lib = "move_m@hurry_butch@a", anim = "move_m@hurry_butch@a"}},
			{label = "Fiero", type = "attitude", data = {lib = "move_m@money", anim = "move_m@money"}},
			{label = "Corsa piccola", type = "attitude", data = {lib = "move_m@quick", anim = "move_m@quick"}},
			{label = "Affamato", type = "attitude", data = {lib = "move_f@maneater", anim = "move_f@maneater"}},
			{label = "Impertinente", type = "attitude", data = {lib = "move_f@sassy", anim = "move_f@sassy"}},	
			{label = "Arrogante", type = "attitude", data = {lib = "move_f@arrogant@a", anim = "move_f@arrogant@a"}},
		}
	},
	{
		name  = 'dancing',
		label = 'Balli',
		items = {
			{label = "Ballo 1", type = "anim", data = {lib = "anim@amb@nightclub@dancers@club_ambientpeds@med-hi_intensity", anim = "mi-hi_amb_club_10_v1_male^6"}},
        	{label = "Ballo 2", type = "anim", data = {lib = "amb@code_human_in_car_mp_actions@dance@bodhi@ds@base", anim = "idle_a_fp"}},
	        {label = "Ballo 3", type = "anim", data = {lib = "amb@code_human_in_car_mp_actions@dance@bodhi@rds@base", anim = "idle_b"}},
    	    {label = "Ballo 4", type = "anim", data = {lib = "amb@code_human_in_car_mp_actions@dance@std@ds@base", anim = "idle_a"}},
        	{label = "Ballo 5", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", anim = "hi_dance_facedj_09_v2_male^6"}},
	        {label = "Ballo 6", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@low_intesnsity", anim = "li_dance_facedj_09_v1_male^6"}},
    	    {label = "Ballo 7", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_hi_intensity", anim = "trans_dance_facedj_hi_to_li_09_v1_male^6"}},
        	{label = "Ballo 8", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_low_intensity", anim = "trans_dance_facedj_li_to_hi_07_v1_male^6"}},
        	{label = "Ballo 9", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", anim = "hi_dance_crowd_13_v2_male^6"}},
        	{label = "Ballo 10", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups_transitions@from_hi_intensity", anim = "trans_dance_crowd_hi_to_li__07_v1_male^6"}},
        	{label = "Ballo 11", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_single_props@hi_intensity", anim = "hi_dance_prop_13_v1_male^6"}},
        	{label = "Ballo 12", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_single_props_transitions@from_med_intensity", anim = "trans_crowd_prop_mi_to_li_11_v1_male^6"}},
        	{label = "Ballo 13", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "med_center_up"}},
        	{label = "Ballo 14", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "med_right_up"}},
        	{label = "Ballo 15", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@low_intensity", anim = "li_dance_crowd_17_v1_male^6"}},
        	{label = "Ballo 16", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_med_intensity", anim = "trans_dance_facedj_mi_to_li_09_v1_male^6"}},
        	{label = "Ballo xD -Rak-", type = "anim", data = {lib = "special_ped@zombie@monologue_4@monologue_4l", anim = "iamtheundead_11"}},
        	{label = "Ballo 17", type = "anim", data = {lib = "timetable@tracy@ig_5@idle_b", anim = "idle_e"}},
    	    {label = "Ballo 18", type = "anim", data = {lib = "mini@strip_club@idles@dj@idle_04", anim = "idle_04"}},
	        {label = "Ballo 19", type = "anim", data = {lib = "special_ped@mountain_dancer@monologue_1@monologue_1a", anim = "mtn_dnc_if_you_want_to_get_to_heaven"}},
        	{label = "Ballo 20", type = "anim", data = {lib = "special_ped@mountain_dancer@monologue_4@monologue_4a", anim = "mnt_dnc_verse"}},
        	{label = "Ballo 21", type = "anim", data = {lib = "special_ped@mountain_dancer@monologue_3@monologue_3a", anim = "mnt_dnc_buttwag"}},
        	{label = "Ballo 22", type = "anim", data = {lib = "anim@amb@nightclub@dancers@black_madonna_entourage@", anim = "hi_dance_facedj_09_v2_male^5"}},
        	{label = "Ballo 23", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_single_props@", anim = "hi_dance_prop_09_v1_male^6"}},
        	{label = "Ballo 24", type = "anim", data = {lib = "anim@amb@nightclub@dancers@dixon_entourage@", anim = "mi_dance_facedj_15_v1_male^4"}},
        	{label = "Ballo 25", type = "anim", data = {lib = "anim@amb@nightclub@dancers@podium_dancers@", anim = "hi_dance_facedj_17_v2_male^5"}},
        	{label = "Ballo 26", type = "anim", data = {lib = "anim@amb@nightclub@dancers@tale_of_us_entourage@", anim = "mi_dance_prop_13_v2_male^4"}},
        	{label = "Ballo 27", type = "anim", data = {lib = "misschinese2_crystalmazemcs1_cs", anim = "dance_loop_tao"}},
        	{label = "Ballo 28", type = "anim", data = {lib = "misschinese2_crystalmazemcs1_ig", anim = "dance_loop_tao"}},
  	      	{label = "Ballo 29", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@uncle_disco", anim = "uncle_disco"}},
        	{label = "Ballo 30", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@raise_the_roof", anim = "raise_the_roof"}},
        	{label = "Ballo 31", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@cats_cradle", anim = "cats_cradle"}},
        	{label = "Ballo 32", type = "anim", data = {lib = "anim@mp_player_intupperbanging_tunes", anim = "idle_a"}},
        	{label = "Ballo 33", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_center"}},
        	{label = "Ballo 34", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "high_center"}},
        	{label = "Ballo 35", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", anim = "high_center"}},
        	{label = "Ballo 36", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@", anim = "trans_dance_facedj_hi_to_mi_11_v1_female^6"}},
        	{label = "Ballo 37", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_hi_intensity", anim = "trans_dance_facedj_hi_to_li_07_v1_female^6"}},
        	{label = "Ballo 38", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "hi_dance_facedj_09_v1_female^6"}},
        	{label = "Ballo 39", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", anim = "hi_dance_crowd_09_v1_female^6"}},
        	{label = "Ballo 40", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_06_base_laz"}},
		}
	},
	{
		name  = 'porn',
		label = 'Pegi 18',
		items = {
			{label = "Uomo farsi fare una pompa in auto", type = "anim", data = {lib = "oddjobs@towing", anim = "m_blow_job_loop"}},
			{label = "Donna fa un pompino in auto", type = "anim", data = {lib = "oddjobs@towing", anim = "f_blow_job_loop"}},
			{label = "Uomo si fa scopare in auto", type = "anim", data = {lib = "mini@prostitutes@sexlow_veh", anim = "low_car_sex_loop_player"}},
			{label = "Femmina scopa in auto", type = "anim", data = {lib = "mini@prostitutes@sexlow_veh", anim = "low_car_sex_loop_female"}},
			{label = "Si gratta le palle", type = "anim", data = {lib = "mp_player_int_uppergrab_crotch", anim = "mp_player_int_grab_crotch"}},
			{label = "Mostra il fascino", type = "anim", data = {lib = "mini@strip_club@idles@stripper", anim = "stripper_idle_02"}},
			{label = "Posa da macho", type = "scenario", data = {anim = "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS"}},
			{label = "Mostra le sue parti del corpo", type = "anim", data = {lib = "mini@strip_club@backroom@", anim = "stripper_b_backroom_idle_b"}},
			{label = "Strip Tease 1", type = "anim", data = {lib = "mini@strip_club@lap_dance@ld_girl_a_song_a_p1", anim = "ld_girl_a_song_a_p1_f"}},
			{label = "Strip Tease 2", type = "anim", data = {lib = "mini@strip_club@private_dance@part2", anim = "priv_dance_p2"}},
			{label = "Anale Femmina", type = "anim", data = {lib = "rcmpaparazzo_2", anim = "shag_loop_poppy"}},
			{label = "Anale Maschio", type = "anim", data = {lib = "rcmpaparazzo_2", anim = "shag_loop_a"}},			
			{label = "Stip Tease da solo", type = "anim", data = {lib = "mini@strip_club@private_dance@part3", anim = "priv_dance_p3"}},
			{label = "Sex 1", type = "anim", data = {lib = "misscarsteal2pimpsex", anim = "pimpsex_punter"}},
			{label = "Sex 2", type = "anim", data = {lib = "misscarsteal2pimpsex", anim = "pimpsex_hooker"}},
			{label = "Sex 3", type = "anim", data = {lib = "rcmpaparazzo_2", anim = "shag_loop_a"}},
			{label = "Sex 4", type = "anim", data = {lib = "mini@prostitutes@sexnorm_veh", anim = "bj_loop_male"}},
			{label = "Sex 5", type = "anim", data = {lib = "mini@prostitutes@sexnorm_veh", anim = "bj_loop_prostitute"}},
			{label = "Sex 6", type = "anim", data = {lib = "random@drunk_driver_2", anim = "cardrunksex_loop_m"}},
			{label = "Sex 7", type = "anim", data = {lib = "random@drunk_driver_2", anim = "cardrunksex_loop_f"}},
		}
	}
}